<?xml version="1.0" ?>
<!-- $Id$ -->

<resourceBundle
  static="false"
  locale="en_US"
  exceptionClassName="net.sf.farrago.util.FarragoException">

<!-- ====================================================================== -->
<!-- Catalog resources 400,000 - 410,000 -->
<!-- ====================================================================== -->

<exception id="400000" name="MissingHomeProperty">
    <text>Installation error: required Java property {0} not set</text>
</exception>

<exception id="400010" name="CatalogUninitialized">
    <text>Installation error: catalog package not found in repository</text>
</exception>

<exception id="400020" name="CatalogFileLockFailed">
    <text>Failed to lock catalog file {0}</text>
</exception>

<exception id="400030" name="CatalogInitTransientFailed">
    <text>Failed to initialize transient portion of catalog</text>
</exception>

<exception id="400040" name="CatalogExternalLoadFailed">
    <text>Failed to access external repository</text>
</exception>

<exception id="400050" name="CatalogExternalInitFailed">
    <text>Failed to initialize external repository</text>
</exception>

<exception id="400060" name="CatalogPropsAccessFailed">
    <text>Failed to access repository storage properties file {0}</text>
</exception>

<!-- ====================================================================== -->
<!-- JDBC resources 410,000 - 420,000 -->
<!-- ====================================================================== -->

<exception id="410000" name="JdbcInvalidTxnState">
    <text>Invalid transaction state</text>
</exception>

<exception id="410010" name="JdbcInvalidUrl">
    <text>Invalid URL:  {0}</text>
</exception>

<!-- ====================================================================== -->
<!-- Validator resources 420,000 - 430,000 -->
<!-- ====================================================================== -->

<exception id="420000" name="ValidatorDuplicateNames">
    <text>Duplicate definition for {0} within {1};
encountered near {2};
earlier definition was near {3}</text>
</exception>

<exception id="420010" name="ValidatorNameInUse">
    <text>{0} already exists within {1};
duplicate name encountered near {2}</text>
</exception>

<exception id="420040" name="ValidatorCharsetUnexpected">
    <text>{0} does not accept a CHARACTER SET specification;
encountered in definition of {1} near {2}</text>
</exception>

<exception id="420050" name="ValidatorPrecRequired">
    <text>{0} requires a precision specification;
encountered in definition of {1} near {2}</text>
</exception>

<exception id="420060" name="ValidatorPrecUnexpected">
    <text>{0} does not accept a precision specification;
encountered in definition of {1} near {2}</text>
</exception>

<exception id="420070" name="ValidatorScaleUnexpected">
    <text>{0} does not accept a scale specification;
encountered in definition of {1} near {2}</text>
</exception>

<exception id="420080" name="ValidatorCharsetUnsupported">
    <text>Character set {0} unsupported;
encountered in definition of {1} near {2}</text>
</exception>

<exception id="420090" name="ValidatorLengthExceeded">
    <text>Character length {0,number,#} exceeds maximum of {1,number,#};
encountered in definition of {2} near {3}</text>
</exception>

<exception id="420100" name="ValidatorPrecisionExceeded">
    <text>Precision {0,number,#} exceeds maximum of {1,number,#};
encountered in definition of {2} near {3}</text>
</exception>

<exception id="420110" name="ValidatorScaleExceeded">
    <text>Scale {0,number,#} exceeds maximum of {1,number,#};
encountered in definition of {2} near {3}</text>
</exception>

<exception id="420120" name="ValidatorUnknownObject">
    <text>Reference to unknown {0};
encountered near {1}</text>
</exception>

<exception id="420130" name="ValidatorUnknownColumn">
    <text>Column {0} not defined in table {1};
encountered near {2}</text>
</exception>

<exception id="420150" name="ValidatorDuplicateClusteredIndex">
    <text>Table {0} already has a clustered index</text>
</exception>

<exception id="420170" name="ValidatorDropRestrict">
    <text>{0} can only be dropped with CASCADE because other objects still reference it</text>
</exception>

<exception id="420180" name="ValidatorDropClusteredIndex">
    <text>Clustered index {0} cannot be dropped;
encountered at {1}</text>
</exception>

<exception id="420190" name="ValidatorNoDefaultSchema">
    <text>No default schema specified; execute SET SCHEMA or use fully qualified names</text>
</exception>

<exception id="420200" name="ValidatorNoPrimaryKey">
    <text>Table {0} must have a PRIMARY KEY</text>
</exception>

<exception id="420210" name="ValidatorMultiplePrimaryKeys">
    <text>Table {0} cannot have more than one PRIMARY KEY</text>
</exception>

<exception id="420220" name="ValidatorIndexBadTable">
    <text>Cannot create index on different table from one being defined;
encountered at {0}</text>
</exception>

<exception id="420230" name="ValidatorBadDefaultClause">
    <text>Invalid DEFAULT clause for column {0};
encountered near {1}</text>
</exception>

<exception id="420240" name="ValidatorBadDefaultType">
    <text>Type mismatch in DEFAULT clause for column {0};
column type family is {1} but default value type family is {2};
encountered near {3}
</text>
</exception>

<exception id="420250" name="ValidatorUnknownSysParam">
    <text>Reference to unknown system parameter {0}</text>
</exception>

<exception id="420260" name="ValidatorSysParamTypeMismatch">
    <text>Type mismatch in value {0} for system parameter {1}</text>
</exception>

<exception id="420270" name="ValidatorImmutableSysParam">
    <text>Cannot change immutable system parameter {0}</text>
</exception>

<exception id="420280" name="ValidatorIndexOnExistingTempTable">
    <text>Cannot create or drop index {0} on existing temporary table {1}</text>
</exception>

<exception id="420290" name="ValidatorBadDefaultParam">
    <text>Cannot reference dynamic parameter in DEFAULT clause for column {0};
encountered near {1}</text>
</exception>

<exception id="420300" name="ValidatorUntranslated">
    <text>{0}</text>
</exception>

<exception id="420310" name="ValidatorViewColumnCountMismatch">
    <text>Column name count does not match query</text>
</exception>

<exception id="420320" name="ValidatorInvalidObjectDefinition">
    <text>Invalid definition for {0}</text>
</exception>

<exception id="420330" name="ValidatorInvalidViewDynamicParam">
    <text>Dynamic parameters are illegal in views</text>
</exception>

<exception id="420340" name="ValidatorSchemaDependencyCycle">
    <text>Schema definition contains view cycle</text>
</exception>

<exception id="420350" name="ValidatorInvalidViewOrderBy">
    <text>ORDER BY is illegal in views</text>
</exception>

<exception id="420360" name="ValidatorDataWrapperInvalid">
    <text>Failed to validate definition for data wrapper {0}</text>
</exception>

<exception id="420360" name="ValidatorDataServerInvalid">
    <text>Failed to validate definition for data server {0}</text>
</exception>

<exception id="420360" name="ValidatorDataServerTableInvalid">
    <text>Failed to validate data server definition for {0}</text>
</exception>

<exception id="420370" name="ValidatorForeignTableLookupFailed">
    <text>Failed to look up foreign table name {0}</text>
</exception>

<exception id="420380" name="ValidatorForeignTableButLocalWrapper">
    <text>Cannot create foreign table {0} using local data wrapper {1}</text>
</exception>

<exception id="420390" name="ValidatorLocalTableButForeignWrapper">
    <text>Cannot create local table {0} using foreign data wrapper {1}</text>
</exception>

<exception id="420400" name="ValidatorForeignWrapperHasLocalImpl">
    <text>Cannot create foreign data wrapper {0} because its library implements local storage</text>
</exception>

<exception id="420410" name="ValidatorLocalWrapperHasForeignImpl">
    <text>Cannot create local data wrapper {0} because its library implements foreign storage</text>
</exception>

<exception id="420420" name="ValidatorCalcUnavailable">
    <text>Requested calculator implementation is unavailable</text>
</exception>

<exception id="420430" name="ValidatorNoConstraintAllowed">
    <text>{0} does not accept a constraint definition</text>
</exception>

<exception id="420440" name="ValidatorRoutineSchemaMismatch">
    <text>Schema {0} for specific name does not match schema {1} for invocation name;
encountered near {2}</text>
</exception>

<exception id="420450" name="ValidatorRoutineDataAccessUnspecified">
    <text>SQL data access must be specified in definition of routine {0};
encountered near {1}</text>
</exception>

<exception id="420460" name="ValidatorInvalidRoutineDynamicParam">
    <text>Dynamic parameters are illegal in routine bodies</text>
</exception>

<exception id="420470" name="ValidatorFunctionOutputParam">
    <text>Parameters to function {0} may not be declared as OUT or INOUT;
encountered near {1}</text>
</exception>

<exception id="420480" name="ValidatorRoutineNoSql">
    <text>Routine {0} with SQL definition cannot specify NO SQL;
encountered near {1}</text>
</exception>

<!-- ====================================================================== -->
<!-- Fennel resources 440,000 - 450,000 -->
<!-- Actual resources are defined separately in Fennel -->
<!-- This range is reserved to avoid overlap -->
<!-- ====================================================================== -->

<exception id="440000" name="FennelUntranslated">
    <text>{0}</text>
</exception>

<!-- ====================================================================== -->
<!-- Execution resources 450,000 - 460,000 -->
<!-- ====================================================================== -->

<exception id="450000" name="NullNotAllowed">
    <text>NOT NULL field cannot be assigned null value</text>
</exception>

<exception id="450010" name="AssignFromFailed">
    <text>Cannot assign ''{0}'' to a {1} value: {2}</text>
</exception>

<exception id="450020" name="ParameterValueTooLong">
    <text>Value ''{0}'' is too long for parameter ''{1}'' of type ''{2}''</text>
</exception>

<exception id="450020" name="ParameterValueIncompatible">
    <text>Cannot assign a value of Java class ''{0}'' to parameter ''{1}'' of type ''{2}''</text>
</exception>

<!-- ====================================================================== -->
<!-- Data wrapper resources 460,000 - 470,000 -->
<!-- ====================================================================== -->

<exception id="460020" name="DataServerInitFailed">
    <text>Failed to initialize data server</text>
</exception>

<exception id="460030" name="ForeignTableAccessFailed">
    <text>Failed to access foreign table {0}</text>
</exception>

<exception id="460040" name="JdbcDriverLoadFailed">
    <text>Could not load JDBC driver class {0}</text>
</exception>

<exception id="460050" name="JdbcDriverTypeInfoFailed">
    <text>Could not obtain type information from  JDBC driver</text>
</exception>

<exception id="460060" name="DataServerRuntimeFailed">
    <text>Failed to access data server for execution</text>
</exception>

<exception id="460080" name="DataServerIndexCreateFailed">
    <text>Failed to create storage for index {0}</text>
</exception>

<exception id="460090" name="DataServerIndexDropFailed">
    <text>Failed to drop storage for index {0}</text>
</exception>

<!-- ====================================================================== -->
<!-- Database/Session resources 470,000 - 480,000 -->
<!-- ====================================================================== -->

<exception id="470000" name="DatabaseLoadFailed">
    <text>Failed to load database</text>
</exception>

<exception id="470010" name="SessionNoCommitInAutocommit">
    <text>Can't COMMIT in auto-commit mode</text>
</exception>

<exception id="470020" name="SessionNoRollbackInAutocommit">
    <text>Can't ROLLBACK in auto-commit mode</text>
</exception>

<exception id="470030" name="SessionDupSavepointName">
    <text>Savepoint name {0} already in use</text>
</exception>

<exception id="470040" name="SessionNoSavepointInAutocommit">
    <text>Can't create SAVEPOINT in auto-commit mode</text>
</exception>

<exception id="470050" name="SessionWrongSavepoint">
    <text>Savepoint {0} is from wrong session</text>
</exception>

<exception id="470060" name="SessionInvalidSavepointId">
    <text>Invalid savepoint ID {0,number,#}</text>
</exception>

<exception id="470070" name="SessionInvalidSavepointName">
    <text>Invalid savepoint name {0}</text>
</exception>

<exception id="470080" name="SessionNoExecuteImmediateParameters">
    <text>Cannot EXECUTE IMMEDIATE a statement with dynamic parameters:  {0}</text>
</exception>

<!-- ====================================================================== -->
<!-- Server resources 480,000 - 490,000 -->
<!-- ====================================================================== -->

<message id="480000" name="ServerLoadingDatabase">
    <text>Loading database...</text>
</message>

<message id="480010" name="ServerStartingNetwork">
    <text>Starting network...</text>
</message>

<message id="480020" name="ServerListening">
    <text>Server now listening for connections on port {0,number,#}; enter !quit to stop</text>
</message>

<message id="480030" name="ServerBadCommand">
    <text>Unknown server command:  {0}</text>
</message>

<message id="480040" name="ServerShuttingDown">
    <text>Server shutting down...</text>
</message>

<message id="480050" name="ServerShutdownComplete">
    <text>Server shutdown complete</text>
</message>

<message id="480060" name="ServerSessionsExist">
    <text>Server sessions are still running; enter !kill to force shutdown</text>
</message>

<!-- ====================================================================== -->
<!-- Plugin resources 490,000 - 500,000 -->
<!-- ====================================================================== -->

<exception id="490000" name="PluginInvalidIntProp">
    <text>Invalid value {0} for integer property {1}</text>
</exception>

<exception id="490010" name="PluginJarLoadFailed">
    <text>Failed to load plugin jar {0}</text>
</exception>

<exception id="490020" name="PluginInitFailed">
    <text>Failed to initialize plugin {0}</text>
</exception>

<!-- ====================================================================== -->
<!-- com.disruptivetech.farrago.calc resources 500,000 - 510,000 -->
<!-- REVIEW jvs 28-Aug-2004:  these are all assertions, so why i18n? -->
<!-- ====================================================================== -->

<exception id="500000" name="ProgramCompilationError">
    <text>Calculator program compilation error: {0}</text>
</exception>

<exception id="500010" name="ProgramImplementationError">
    <text>Calculator program implementation error: {0}</text>
</exception>

<exception id="500020" name="CompilationAssertionError">
    <text>Calculator program compilation assertion error: {0}</text>
</exception>

<!-- End of last error section ============================================ -->

</resourceBundle>

<!-- End FarragoResource.xml -->
